name: edumarshal
description: A mini app for edumarshal
version: 1.0.3+28
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^7.8.3
  barcode_widget: ^2.0.4
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  duration: ^3.0.13
  flash: ^3.0.5+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  #  flutter_pdfview: ^1.3.2
  flutter_riverpod: ^2.4.0
  google_fonts: ^6.1.0
  hero_animation: ^1.1.4
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.1.13
  in_app_review: ^2.0.8
  in_app_update: ^4.2.2
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  lottie: ^2.7.0
  #  paged_vertical_calendar: ^1.1.6
  path: ^1.8.3
  path_provider: ^2.1.1
  platform_info: ^4.0.2
  responsive_framework: ^1.1.1
  sqflite: ^2.3.0
  table_calendar: ^3.0.9
  talker_dio_logger: ^2.3.0
  talker_flutter: ^3.2.7
  velocity_x: ^4.1.1
  rate_my_app: ^2.0.0
  flutter_secure_storage: ^9.0.0
  google_mobile_ads: ^4.0.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.4
  firebase_performance: ^0.9.4+4
  shared_preferences: ^2.2.3
  open_store: ^0.5.0
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  gif_view: ^0.4.3
  sentry_flutter: ^8.1.0
  fl_chart: ^0.68.0
dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_lint: ^2.1.0
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
#    - assets/icons/
#    - assets/fonts/
