// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa5KecE-RtOKjlvmpnFqYH7v0bTxh9f7I',
    appId: '1:413399910247:web:ba26e7ad0f707cc6f651c2',
    messagingSenderId: '413399910247',
    projectId: 'edumarshal-go',
    authDomain: 'edumarshal-go.firebaseapp.com',
    storageBucket: 'edumarshal-go.appspot.com',
    measurementId: 'G-F7T5JCS5D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC27BLp93cdFDZDjlpyCT15_QEL2AiRjjw',
    appId: '1:413399910247:android:765e2aedd107ff91f651c2',
    messagingSenderId: '413399910247',
    projectId: 'edumarshal-go',
    storageBucket: 'edumarshal-go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdA7dNDApNmC0q1Ee-zd6lND9WU5KuAtE',
    appId: '1:413399910247:ios:ef772ca5f9b4d463f651c2',
    messagingSenderId: '413399910247',
    projectId: 'edumarshal-go',
    storageBucket: 'edumarshal-go.appspot.com',
    iosBundleId: 'com.akgec.edumarshal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdA7dNDApNmC0q1Ee-zd6lND9WU5KuAtE',
    appId: '1:413399910247:ios:ef772ca5f9b4d463f651c2',
    messagingSenderId: '413399910247',
    projectId: 'edumarshal-go',
    storageBucket: 'edumarshal-go.appspot.com',
    iosBundleId: 'com.akgec.edumarshal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa5KecE-RtOKjlvmpnFqYH7v0bTxh9f7I',
    appId: '1:413399910247:web:899b0678f7de6153f651c2',
    messagingSenderId: '413399910247',
    projectId: 'edumarshal-go',
    authDomain: 'edumarshal-go.firebaseapp.com',
    storageBucket: 'edumarshal-go.appspot.com',
    measurementId: 'G-6G2F3H0QT0',
  );
}
