// To parse this JSON data, do
//
//     final profileData = profileDataFromJson(jsonString);

import 'dart:convert';

ProfileData profileDataFromJson(Map<String, dynamic> str) =>
    ProfileData.fromJson(str);

String? profileDataToJson(ProfileData data) => json.encode(data.toJson());

class ProfileData {
  int? userId;
  String? loginName;
  String? firstName;
  String? middleName;
  String? lastName;
  int? courseId;
  int? batchId;
  String? admissionNumber;
  String? rollNumber;
  String? email;
  dynamic alternateStudentEmail;
  String? userDetails;
  dynamic gardiunInfo;
  String? userExtraRecord;
  DateTime admissionDate;
  DateTime dob;
  int? profilePictureId;
  bool userStatus;
  dynamic inactiveDate;
  dynamic departmentId;
  int? categoryId;
  int? studentSequence;
  dynamic activeSubStatus;
  dynamic activeStatus;
  dynamic modeOfAdmission;
  dynamic subModeAdmission;
  dynamic isEws;
  dynamic isTfw;
  int? branchId;
  dynamic employeeNumber;
  String? aadhaarNumber;
  String? smsMobileNumber;
  String? parentMobileNumber;
  String? mothersMobileNumber;
  dynamic minority;
  dynamic fatherAadharnumber;
  dynamic motherAadharnumber;
  dynamic fatherPanNumber;
  dynamic motherPanNumber;
  dynamic fatherEmail;
  String? fatherName;
  String? motherName;
  String? address;
  String? gender;
  dynamic motherEmail;
  dynamic physical;
  dynamic previousEducationClass;
  dynamic medical;
  dynamic transportMode;
  dynamic routeNumber;
  dynamic transportPickPoint;
  dynamic registrationNumberNine;
  dynamic rollNumberTenth;
  dynamic registrationNumberEleven;
  dynamic rollNumberTwelve;
  dynamic boardRegistrationNumber;
  dynamic house;
  dynamic height;
  dynamic weight;
  String? bloodGroup;
  dynamic birthPlace;
  dynamic nation;
  dynamic motherTongue;
  dynamic bankAccountNo;
  dynamic isBpl;
  dynamic ifscCode;
  dynamic uIdNo;
  dynamic caste;
  dynamic religion;
  dynamic castCertificateNumber;
  dynamic foodSecurityCardNumber;
  dynamic dateOfAdmission;
  dynamic classOfAdmission;
  dynamic registrationDate;
  dynamic addedBy;
  DateTime dateTimeStampIns;
  dynamic loginStatus;
  int? enquiryId;
  DateTime dateTimeStamp;
  bool isDeleted;
  int? migrationStatus;
  bool remember;
  bool firstTimePasswordReset;
  dynamic social;
  int? previousClassUserId;
  String? bioUserId;
  int? financialYear;
  dynamic familyId;
  dynamic tenthClassPercentage;
  dynamic twelthClassPercentage;
  bool scholarshipOffered;
  dynamic scholarshipAmount;
  dynamic alumniId;
  String? deviceId;
  dynamic userType;
  dynamic viewOnlyRight;
  dynamic isProvisionalStudent;
  dynamic admissionFormNumber;
  dynamic parentOccupation;
  dynamic motherbusiness;
  dynamic fatherOfficeAdd;
  dynamic motherOfficeAdd;
  dynamic fatherBusinessName;
  dynamic motherBusinessName;
  dynamic parentIncome;
  dynamic mothersIncome;
  dynamic perobtained;
  dynamic attendedschool;
  dynamic lastSchoolStudied;
  dynamic placementCategory;
  dynamic enrollmentNumber;
  dynamic udf;
  dynamic udf1;
  dynamic udf2;
  dynamic admissionGroupId;
  dynamic lastWorkingDate;
  dynamic bankName;
  int? feeScheduleId;
  bool isEntryFromSelfMigration;
  bool transportSelected;
  int? transportVehicleId;
  int? routeStopId;
  int? finalRouteId;
  dynamic transportFare;
  dynamic fullName;
  dynamic firstFeeReceiptNumber;
  dynamic firstFeeAmount;
  dynamic teacherShortName;
  dynamic subjectsMarks;
  int? userGrandTotalMarks;
  int? userGrandTotalPercentage;
  int? studentFirstTermPercentage;
  int? studentSecondTermPercentage;
  dynamic userGrandResult;
  dynamic remark;
  dynamic statusDescription;
  bool isProfileImageUpdate;
  int? businessDays;
  int? templateId;
  dynamic message;
  bool convertToStudent;
  String? dobInWord;
  bool status;
  dynamic guid;
  dynamic categoryName;
  dynamic className;
  bool showNoDues;
  dynamic enquiryList;
  dynamic fieldValue;
  dynamic healthData;
  dynamic enquiryBrochureCost;
  dynamic customData;
  dynamic userAchievement;
  dynamic userInternshipDetails;
  dynamic employeeAchievementDetails;
  bool isAbsent;
  bool isSelfMigrated;
  int? studentAdmissionType;
  int? title;
  dynamic selectedFeeSchedule;
  dynamic subjectList;
  dynamic designationId;
  int? employementType;
  dynamic hierarcy;
  dynamic employeeDesignationList;
  dynamic empDesList;
  dynamic employeeDesignationNames;
  bool isUpdateUserName;
  dynamic updatedUserName;
  dynamic phone;
  dynamic fatherOccupation;
  dynamic twelfthpercentageObtained;
  int? presentDayCount;
  int? absentDayCount;
  dynamic presentPercentage;
  dynamic empAbsentDateList;
  List<dynamic> disciplineList;
  dynamic parentMeetingList;
  dynamic hodMeetingList;
  dynamic userJsonValues;
  dynamic tenthpercentageObtained;
  int? empRole;
  dynamic inchargeName;
  dynamic referredBy;
  dynamic transferDate;
  dynamic marriageAnniversaryDate;
  dynamic userData;
  bool errorWhileSendingMail;
  bool emailAddressIsNotValid;
  dynamic preAdmissionCustomData;
  dynamic errorMessage;
  dynamic allocatedHostelName;
  dynamic reportCardStatus;
  int? reportCardId;
  String? dobInText;
  dynamic courseName;
  dynamic semester;
  dynamic empCategoryCode;
  dynamic attendanceDateRange;
  String? parentFullName;
  String? motherFullName;
  String? addressLine1;
  dynamic addressLine2;
  dynamic leavingReason;
  dynamic uanNumber;
  dynamic pfNumber;
  dynamic officeEmail;
  dynamic smartCardNumber;
  dynamic firstBusAttendantName;
  dynamic firstBusAttendantMobileNumber;
  dynamic totalSalary;
  dynamic schemeId;
  dynamic appoinmentId;
  dynamic appoinmentFrom;
  int? lectureBased;
  dynamic confirmationDate;
  dynamic renewalDate;
  dynamic hostelId;
  dynamic documentList;
  dynamic optionalSubjectsLists;
  dynamic studentEnquiryDetail;
  dynamic studentFeeSubmissionDetail;
  dynamic studentShortName;
  dynamic studentNameInReportCard;
  dynamic batchName;
  dynamic incrimentedEmployeeNumber;
  dynamic schoolName;
  dynamic sectionName;

  ProfileData({
    required this.userId,
    required this.loginName,
    required this.firstName,
    required this.middleName,
    required this.lastName,
    required this.courseId,
    required this.batchId,
    required this.admissionNumber,
    required this.rollNumber,
    required this.email,
    required this.alternateStudentEmail,
    required this.userDetails,
    required this.gardiunInfo,
    required this.userExtraRecord,
    required this.admissionDate,
    required this.dob,
    required this.profilePictureId,
    required this.userStatus,
    required this.inactiveDate,
    required this.departmentId,
    required this.categoryId,
    required this.studentSequence,
    required this.activeSubStatus,
    required this.activeStatus,
    required this.modeOfAdmission,
    required this.subModeAdmission,
    required this.isEws,
    required this.isTfw,
    required this.branchId,
    required this.employeeNumber,
    required this.aadhaarNumber,
    required this.smsMobileNumber,
    required this.parentMobileNumber,
    required this.mothersMobileNumber,
    required this.minority,
    required this.fatherAadharnumber,
    required this.motherAadharnumber,
    required this.fatherPanNumber,
    required this.motherPanNumber,
    required this.fatherEmail,
    required this.fatherName,
    required this.motherName,
    required this.address,
    required this.gender,
    required this.motherEmail,
    required this.physical,
    required this.previousEducationClass,
    required this.medical,
    required this.transportMode,
    required this.routeNumber,
    required this.transportPickPoint,
    required this.registrationNumberNine,
    required this.rollNumberTenth,
    required this.registrationNumberEleven,
    required this.rollNumberTwelve,
    required this.boardRegistrationNumber,
    required this.house,
    required this.height,
    required this.weight,
    required this.bloodGroup,
    required this.birthPlace,
    required this.nation,
    required this.motherTongue,
    required this.bankAccountNo,
    required this.isBpl,
    required this.ifscCode,
    required this.uIdNo,
    required this.caste,
    required this.religion,
    required this.castCertificateNumber,
    required this.foodSecurityCardNumber,
    required this.dateOfAdmission,
    required this.classOfAdmission,
    required this.registrationDate,
    required this.addedBy,
    required this.dateTimeStampIns,
    required this.loginStatus,
    required this.enquiryId,
    required this.dateTimeStamp,
    required this.isDeleted,
    required this.migrationStatus,
    required this.remember,
    required this.firstTimePasswordReset,
    required this.social,
    required this.previousClassUserId,
    required this.bioUserId,
    required this.financialYear,
    required this.familyId,
    required this.tenthClassPercentage,
    required this.twelthClassPercentage,
    required this.scholarshipOffered,
    required this.scholarshipAmount,
    required this.alumniId,
    required this.deviceId,
    required this.userType,
    required this.viewOnlyRight,
    required this.isProvisionalStudent,
    required this.admissionFormNumber,
    required this.parentOccupation,
    required this.motherbusiness,
    required this.fatherOfficeAdd,
    required this.motherOfficeAdd,
    required this.fatherBusinessName,
    required this.motherBusinessName,
    required this.parentIncome,
    required this.mothersIncome,
    required this.perobtained,
    required this.attendedschool,
    required this.lastSchoolStudied,
    required this.placementCategory,
    required this.enrollmentNumber,
    required this.udf,
    required this.udf1,
    required this.udf2,
    required this.admissionGroupId,
    required this.lastWorkingDate,
    required this.bankName,
    required this.feeScheduleId,
    required this.isEntryFromSelfMigration,
    required this.transportSelected,
    required this.transportVehicleId,
    required this.routeStopId,
    required this.finalRouteId,
    required this.transportFare,
    required this.fullName,
    required this.firstFeeReceiptNumber,
    required this.firstFeeAmount,
    required this.teacherShortName,
    required this.subjectsMarks,
    required this.userGrandTotalMarks,
    required this.userGrandTotalPercentage,
    required this.studentFirstTermPercentage,
    required this.studentSecondTermPercentage,
    required this.userGrandResult,
    required this.remark,
    required this.statusDescription,
    required this.isProfileImageUpdate,
    required this.businessDays,
    required this.templateId,
    required this.message,
    required this.convertToStudent,
    required this.dobInWord,
    required this.status,
    required this.guid,
    required this.categoryName,
    required this.className,
    required this.showNoDues,
    required this.enquiryList,
    required this.fieldValue,
    required this.healthData,
    required this.enquiryBrochureCost,
    required this.customData,
    required this.userAchievement,
    required this.userInternshipDetails,
    required this.employeeAchievementDetails,
    required this.isAbsent,
    required this.isSelfMigrated,
    required this.studentAdmissionType,
    required this.title,
    required this.selectedFeeSchedule,
    required this.subjectList,
    required this.designationId,
    required this.employementType,
    required this.hierarcy,
    required this.employeeDesignationList,
    required this.empDesList,
    required this.employeeDesignationNames,
    required this.isUpdateUserName,
    required this.updatedUserName,
    required this.phone,
    required this.fatherOccupation,
    required this.twelfthpercentageObtained,
    required this.presentDayCount,
    required this.absentDayCount,
    required this.presentPercentage,
    required this.empAbsentDateList,
    required this.disciplineList,
    required this.parentMeetingList,
    required this.hodMeetingList,
    required this.userJsonValues,
    required this.tenthpercentageObtained,
    required this.empRole,
    required this.inchargeName,
    required this.referredBy,
    required this.transferDate,
    required this.marriageAnniversaryDate,
    required this.userData,
    required this.errorWhileSendingMail,
    required this.emailAddressIsNotValid,
    required this.preAdmissionCustomData,
    required this.errorMessage,
    required this.allocatedHostelName,
    required this.reportCardStatus,
    required this.reportCardId,
    required this.dobInText,
    required this.courseName,
    required this.semester,
    required this.empCategoryCode,
    required this.attendanceDateRange,
    required this.parentFullName,
    required this.motherFullName,
    required this.addressLine1,
    required this.addressLine2,
    required this.leavingReason,
    required this.uanNumber,
    required this.pfNumber,
    required this.officeEmail,
    required this.smartCardNumber,
    required this.firstBusAttendantName,
    required this.firstBusAttendantMobileNumber,
    required this.totalSalary,
    required this.schemeId,
    required this.appoinmentId,
    required this.appoinmentFrom,
    required this.lectureBased,
    required this.confirmationDate,
    required this.renewalDate,
    required this.hostelId,
    required this.documentList,
    required this.optionalSubjectsLists,
    required this.studentEnquiryDetail,
    required this.studentFeeSubmissionDetail,
    required this.studentShortName,
    required this.studentNameInReportCard,
    required this.batchName,
    required this.incrimentedEmployeeNumber,
    required this.schoolName,
    required this.sectionName,
  });

  factory ProfileData.fromJson(Map<String, dynamic> json) => ProfileData(
        userId: json["userId"],
        loginName: json["loginName"],
        firstName: json["firstName"],
        middleName: json["middleName"],
        lastName: json["lastName"],
        courseId: json["courseId"],
        batchId: json["batchId"],
        admissionNumber: json["admissionNumber"],
        rollNumber: json["rollNumber"],
        email: json["email"],
        alternateStudentEmail: json["alternateStudentEmail"],
        userDetails: json["userDetails"],
        gardiunInfo: json["gardiunInfo"],
        userExtraRecord: json["userExtraRecord"],
        admissionDate: DateTime.parse(json["admissionDate"]),
        dob: DateTime.parse(json["dob"]),
        profilePictureId: json["profilePictureId"],
        userStatus: json["userStatus"],
        inactiveDate: json["inactiveDate"],
        departmentId: json["departmentId"],
        categoryId: json["categoryId"],
        studentSequence: json["studentSequence"],
        activeSubStatus: json["activeSubStatus"],
        activeStatus: json["activeStatus"],
        modeOfAdmission: json["modeOfAdmission"],
        subModeAdmission: json["subModeAdmission"],
        isEws: json["isEWS"],
        isTfw: json["isTFW"],
        branchId: json["branchId"],
        employeeNumber: json["employeeNumber"],
        aadhaarNumber: json["aadhaarNumber"],
        smsMobileNumber: json["smsMobileNumber"],
        parentMobileNumber: json["parentMobileNumber"],
        mothersMobileNumber: json["mothersMobileNumber"],
        minority: json["minority"],
        fatherAadharnumber: json["fatherAadharnumber"],
        motherAadharnumber: json["motherAadharnumber"],
        fatherPanNumber: json["fatherPanNumber"],
        motherPanNumber: json["motherPanNumber"],
        fatherEmail: json["fatherEmail"],
        fatherName: json["fatherName"],
        motherName: json["motherName"],
        address: json["address"],
        gender: json["gender"],
        motherEmail: json["motherEmail"],
        physical: json["physical"],
        previousEducationClass: json["previousEducationClass"],
        medical: json["medical"],
        transportMode: json["transportMode"],
        routeNumber: json["routeNumber"],
        transportPickPoint: json["transportPickPoint"],
        registrationNumberNine: json["registrationNumberNine"],
        rollNumberTenth: json["rollNumberTenth"],
        registrationNumberEleven: json["registrationNumberEleven"],
        rollNumberTwelve: json["rollNumberTwelve"],
        boardRegistrationNumber: json["boardRegistrationNumber"],
        house: json["house"],
        height: json["height"],
        weight: json["weight"],
        bloodGroup: json["bloodGroup"],
        birthPlace: json["birthPlace"],
        nation: json["nation"],
        motherTongue: json["motherTongue"],
        bankAccountNo: json["bankAccountNo"],
        isBpl: json["isBPL"],
        ifscCode: json["ifscCode"],
        uIdNo: json["uIdNo"],
        caste: json["caste"],
        religion: json["religion"],
        castCertificateNumber: json["castCertificateNumber"],
        foodSecurityCardNumber: json["foodSecurityCardNumber"],
        dateOfAdmission: json["dateOfAdmission"],
        classOfAdmission: json["classOfAdmission"],
        registrationDate: json["registrationDate"],
        addedBy: json["addedBy"],
        dateTimeStampIns: DateTime.parse(json["dateTimeStampIns"]),
        loginStatus: json["loginStatus"],
        enquiryId: json["enquiryId"],
        dateTimeStamp: DateTime.parse(json["dateTimeStamp"]),
        isDeleted: json["isDeleted"],
        migrationStatus: json["migrationStatus"],
        remember: json["remember"],
        firstTimePasswordReset: json["firstTimePasswordReset"],
        social: json["social"],
        previousClassUserId: json["previousClassUserId"],
        bioUserId: json["bioUserId"],
        financialYear: json["financialYear"],
        familyId: json["familyId"],
        tenthClassPercentage: json["tenthClassPercentage"],
        twelthClassPercentage: json["twelthClassPercentage"],
        scholarshipOffered: json["scholarshipOffered"],
        scholarshipAmount: json["scholarshipAmount"],
        alumniId: json["alumniId"],
        deviceId: json["deviceId"],
        userType: json["userType"],
        viewOnlyRight: json["viewOnlyRight"],
        isProvisionalStudent: json["isProvisionalStudent"],
        admissionFormNumber: json["admissionFormNumber"],
        parentOccupation: json["parentOccupation"],
        motherbusiness: json["motherbusiness"],
        fatherOfficeAdd: json["fatherOfficeAdd"],
        motherOfficeAdd: json["motherOfficeAdd"],
        fatherBusinessName: json["fatherBusinessName"],
        motherBusinessName: json["motherBusinessName"],
        parentIncome: json["parentIncome"],
        mothersIncome: json["mothersIncome"],
        perobtained: json["perobtained"],
        attendedschool: json["attendedschool"],
        lastSchoolStudied: json["lastSchoolStudied"],
        placementCategory: json["placementCategory"],
        enrollmentNumber: json["enrollmentNumber"],
        udf: json["udf"],
        udf1: json["udf1"],
        udf2: json["udf2"],
        admissionGroupId: json["admissionGroupId"],
        lastWorkingDate: json["lastWorkingDate"],
        bankName: json["bankName"],
        feeScheduleId: json["feeScheduleId"],
        isEntryFromSelfMigration: json["isEntryFromSelfMigration"],
        transportSelected: json["transportSelected"],
        transportVehicleId: json["transportVehicleId"],
        routeStopId: json["routeStopId"],
        finalRouteId: json["finalRouteId"],
        transportFare: json["transportFare"],
        fullName: json["fullName"],
        firstFeeReceiptNumber: json["firstFeeReceiptNumber"],
        firstFeeAmount: json["firstFeeAmount"],
        teacherShortName: json["teacherShortName"],
        subjectsMarks: json["subjectsMarks"],
        userGrandTotalMarks: json["userGrandTotalMarks"],
        userGrandTotalPercentage: json["userGrandTotalPercentage"],
        studentFirstTermPercentage: json["studentFirstTermPercentage"],
        studentSecondTermPercentage: json["studentSecondTermPercentage"],
        userGrandResult: json["userGrandResult"],
        remark: json["remark"],
        statusDescription: json["statusDescription"],
        isProfileImageUpdate: json["isProfileImageUpdate"],
        businessDays: json["businessDays"],
        templateId: json["templateId"],
        message: json["message"],
        convertToStudent: json["convertToStudent"],
        dobInWord: json["dobInWord"],
        status: json["status"],
        guid: json["guid"],
        categoryName: json["categoryName"],
        className: json["className"],
        showNoDues: json["showNoDues"],
        enquiryList: json["enquiryList"],
        fieldValue: json["fieldValue"],
        healthData: json["healthData"],
        enquiryBrochureCost: json["enquiryBrochureCost"],
        customData: json["customData"],
        userAchievement: json["userAchievement"],
        userInternshipDetails: json["userInternshipDetails"],
        employeeAchievementDetails: json["employeeAchievementDetails"],
        isAbsent: json["isAbsent"],
        isSelfMigrated: json["isSelfMigrated"],
        studentAdmissionType: json["studentAdmissionType"],
        title: json["title"],
        selectedFeeSchedule: json["selectedFeeSchedule"],
        subjectList: json["subjectList"],
        designationId: json["designationId"],
        employementType: json["employementType"],
        hierarcy: json["hierarcy"],
        employeeDesignationList: json["employeeDesignationList"],
        empDesList: json["empDesList"],
        employeeDesignationNames: json["employeeDesignationNames"],
        isUpdateUserName: json["isUpdateUserName"],
        updatedUserName: json["updatedUserName"],
        phone: json["phone"],
        fatherOccupation: json["fatherOccupation"],
        twelfthpercentageObtained: json["twelfthpercentageObtained"],
        presentDayCount: json["presentDayCount"],
        absentDayCount: json["absentDayCount"],
        presentPercentage: json["presentPercentage"],
        empAbsentDateList: json["empAbsentDateList"],
        disciplineList:
            List<dynamic>.from(json["disciplineList"].map((x) => x)),
        parentMeetingList: json["parentMeetingList"],
        hodMeetingList: json["hodMeetingList"],
        userJsonValues: json["userJsonValues"],
        tenthpercentageObtained: json["tenthpercentageObtained"],
        empRole: json["empRole"],
        inchargeName: json["inchargeName"],
        referredBy: json["referredBy"],
        transferDate: json["transferDate"],
        marriageAnniversaryDate: json["marriageAnniversaryDate"],
        userData: json["userData"],
        errorWhileSendingMail: json["errorWhileSendingMail"],
        emailAddressIsNotValid: json["emailAddressIsNotValid"],
        preAdmissionCustomData: json["preAdmissionCustomData"],
        errorMessage: json["errorMessage"],
        allocatedHostelName: json["allocatedHostelName"],
        reportCardStatus: json["reportCardStatus"],
        reportCardId: json["reportCardId"],
        dobInText: json["dobInText"],
        courseName: json["courseName"],
        semester: json["semester"],
        empCategoryCode: json["empCategoryCode"],
        attendanceDateRange: json["attendanceDateRange"],
        parentFullName: json["parentFullName"],
        motherFullName: json["motherFullName"],
        addressLine1: json["addressLine1"],
        addressLine2: json["addressLine2"],
        leavingReason: json["leavingReason"],
        uanNumber: json["uanNumber"],
        pfNumber: json["pfNumber"],
        officeEmail: json["officeEmail"],
        smartCardNumber: json["smartCardNumber"],
        firstBusAttendantName: json["firstBusAttendantName"],
        firstBusAttendantMobileNumber: json["firstBusAttendantMobileNumber"],
        totalSalary: json["totalSalary"],
        schemeId: json["schemeId"],
        appoinmentId: json["appoinmentId"],
        appoinmentFrom: json["appoinmentFrom"],
        lectureBased: json["lectureBased"],
        confirmationDate: json["confirmationDate"],
        renewalDate: json["renewalDate"],
        hostelId: json["hostelId"],
        documentList: json["documentList"],
        optionalSubjectsLists: json["optionalSubjectsLists"],
        studentEnquiryDetail: json["studentEnquiryDetail"],
        studentFeeSubmissionDetail: json["studentFeeSubmissionDetail"],
        studentShortName: json["studentShortName"],
        studentNameInReportCard: json["studentNameInReportCard"],
        batchName: json["batchName"],
        incrimentedEmployeeNumber: json["incrimentedEmployeeNumber"],
        schoolName: json["schoolName"],
        sectionName: json["sectionName"],
      );

  Map<String, dynamic> toJson() => {
        "userId": userId,
        "loginName": loginName,
        "firstName": firstName,
        "middleName": middleName,
        "lastName": lastName,
        "courseId": courseId,
        "batchId": batchId,
        "admissionNumber": admissionNumber,
        "rollNumber": rollNumber,
        "email": email,
        "alternateStudentEmail": alternateStudentEmail,
        "userDetails": userDetails,
        "gardiunInfo": gardiunInfo,
        "userExtraRecord": userExtraRecord,
        "admissionDate": admissionDate.toIso8601String(),
        "dob": dob.toIso8601String(),
        "profilePictureId": profilePictureId,
        "userStatus": userStatus,
        "inactiveDate": inactiveDate,
        "departmentId": departmentId,
        "categoryId": categoryId,
        "studentSequence": studentSequence,
        "activeSubStatus": activeSubStatus,
        "activeStatus": activeStatus,
        "modeOfAdmission": modeOfAdmission,
        "subModeAdmission": subModeAdmission,
        "isEWS": isEws,
        "isTFW": isTfw,
        "branchId": branchId,
        "employeeNumber": employeeNumber,
        "aadhaarNumber": aadhaarNumber,
        "smsMobileNumber": smsMobileNumber,
        "parentMobileNumber": parentMobileNumber,
        "mothersMobileNumber": mothersMobileNumber,
        "minority": minority,
        "fatherAadharnumber": fatherAadharnumber,
        "motherAadharnumber": motherAadharnumber,
        "fatherPanNumber": fatherPanNumber,
        "motherPanNumber": motherPanNumber,
        "fatherEmail": fatherEmail,
        "fatherName": fatherName,
        "motherName": motherName,
        "address": address,
        "gender": gender,
        "motherEmail": motherEmail,
        "physical": physical,
        "previousEducationClass": previousEducationClass,
        "medical": medical,
        "transportMode": transportMode,
        "routeNumber": routeNumber,
        "transportPickPoint": transportPickPoint,
        "registrationNumberNine": registrationNumberNine,
        "rollNumberTenth": rollNumberTenth,
        "registrationNumberEleven": registrationNumberEleven,
        "rollNumberTwelve": rollNumberTwelve,
        "boardRegistrationNumber": boardRegistrationNumber,
        "house": house,
        "height": height,
        "weight": weight,
        "bloodGroup": bloodGroup,
        "birthPlace": birthPlace,
        "nation": nation,
        "motherTongue": motherTongue,
        "bankAccountNo": bankAccountNo,
        "isBPL": isBpl,
        "ifscCode": ifscCode,
        "uIdNo": uIdNo,
        "caste": caste,
        "religion": religion,
        "castCertificateNumber": castCertificateNumber,
        "foodSecurityCardNumber": foodSecurityCardNumber,
        "dateOfAdmission": dateOfAdmission,
        "classOfAdmission": classOfAdmission,
        "registrationDate": registrationDate,
        "addedBy": addedBy,
        "dateTimeStampIns": dateTimeStampIns.toIso8601String(),
        "loginStatus": loginStatus,
        "enquiryId": enquiryId,
        "dateTimeStamp": dateTimeStamp.toIso8601String(),
        "isDeleted": isDeleted,
        "migrationStatus": migrationStatus,
        "remember": remember,
        "firstTimePasswordReset": firstTimePasswordReset,
        "social": social,
        "previousClassUserId": previousClassUserId,
        "bioUserId": bioUserId,
        "financialYear": financialYear,
        "familyId": familyId,
        "tenthClassPercentage": tenthClassPercentage,
        "twelthClassPercentage": twelthClassPercentage,
        "scholarshipOffered": scholarshipOffered,
        "scholarshipAmount": scholarshipAmount,
        "alumniId": alumniId,
        "deviceId": deviceId,
        "userType": userType,
        "viewOnlyRight": viewOnlyRight,
        "isProvisionalStudent": isProvisionalStudent,
        "admissionFormNumber": admissionFormNumber,
        "parentOccupation": parentOccupation,
        "motherbusiness": motherbusiness,
        "fatherOfficeAdd": fatherOfficeAdd,
        "motherOfficeAdd": motherOfficeAdd,
        "fatherBusinessName": fatherBusinessName,
        "motherBusinessName": motherBusinessName,
        "parentIncome": parentIncome,
        "mothersIncome": mothersIncome,
        "perobtained": perobtained,
        "attendedschool": attendedschool,
        "lastSchoolStudied": lastSchoolStudied,
        "placementCategory": placementCategory,
        "enrollmentNumber": enrollmentNumber,
        "udf": udf,
        "udf1": udf1,
        "udf2": udf2,
        "admissionGroupId": admissionGroupId,
        "lastWorkingDate": lastWorkingDate,
        "bankName": bankName,
        "feeScheduleId": feeScheduleId,
        "isEntryFromSelfMigration": isEntryFromSelfMigration,
        "transportSelected": transportSelected,
        "transportVehicleId": transportVehicleId,
        "routeStopId": routeStopId,
        "finalRouteId": finalRouteId,
        "transportFare": transportFare,
        "fullName": fullName,
        "firstFeeReceiptNumber": firstFeeReceiptNumber,
        "firstFeeAmount": firstFeeAmount,
        "teacherShortName": teacherShortName,
        "subjectsMarks": subjectsMarks,
        "userGrandTotalMarks": userGrandTotalMarks,
        "userGrandTotalPercentage": userGrandTotalPercentage,
        "studentFirstTermPercentage": studentFirstTermPercentage,
        "studentSecondTermPercentage": studentSecondTermPercentage,
        "userGrandResult": userGrandResult,
        "remark": remark,
        "statusDescription": statusDescription,
        "isProfileImageUpdate": isProfileImageUpdate,
        "businessDays": businessDays,
        "templateId": templateId,
        "message": message,
        "convertToStudent": convertToStudent,
        "dobInWord": dobInWord,
        "status": status,
        "guid": guid,
        "categoryName": categoryName,
        "className": className,
        "showNoDues": showNoDues,
        "enquiryList": enquiryList,
        "fieldValue": fieldValue,
        "healthData": healthData,
        "enquiryBrochureCost": enquiryBrochureCost,
        "customData": customData,
        "userAchievement": userAchievement,
        "userInternshipDetails": userInternshipDetails,
        "employeeAchievementDetails": employeeAchievementDetails,
        "isAbsent": isAbsent,
        "isSelfMigrated": isSelfMigrated,
        "studentAdmissionType": studentAdmissionType,
        "title": title,
        "selectedFeeSchedule": selectedFeeSchedule,
        "subjectList": subjectList,
        "designationId": designationId,
        "employementType": employementType,
        "hierarcy": hierarcy,
        "employeeDesignationList": employeeDesignationList,
        "empDesList": empDesList,
        "employeeDesignationNames": employeeDesignationNames,
        "isUpdateUserName": isUpdateUserName,
        "updatedUserName": updatedUserName,
        "phone": phone,
        "fatherOccupation": fatherOccupation,
        "twelfthpercentageObtained": twelfthpercentageObtained,
        "presentDayCount": presentDayCount,
        "absentDayCount": absentDayCount,
        "presentPercentage": presentPercentage,
        "empAbsentDateList": empAbsentDateList,
        "disciplineList": List<dynamic>.from(disciplineList.map((x) => x)),
        "parentMeetingList": parentMeetingList,
        "hodMeetingList": hodMeetingList,
        "userJsonValues": userJsonValues,
        "tenthpercentageObtained": tenthpercentageObtained,
        "empRole": empRole,
        "inchargeName": inchargeName,
        "referredBy": referredBy,
        "transferDate": transferDate,
        "marriageAnniversaryDate": marriageAnniversaryDate,
        "userData": userData,
        "errorWhileSendingMail": errorWhileSendingMail,
        "emailAddressIsNotValid": emailAddressIsNotValid,
        "preAdmissionCustomData": preAdmissionCustomData,
        "errorMessage": errorMessage,
        "allocatedHostelName": allocatedHostelName,
        "reportCardStatus": reportCardStatus,
        "reportCardId": reportCardId,
        "dobInText": dobInText,
        "courseName": courseName,
        "semester": semester,
        "empCategoryCode": empCategoryCode,
        "attendanceDateRange": attendanceDateRange,
        "parentFullName": parentFullName,
        "motherFullName": motherFullName,
        "addressLine1": addressLine1,
        "addressLine2": addressLine2,
        "leavingReason": leavingReason,
        "uanNumber": uanNumber,
        "pfNumber": pfNumber,
        "officeEmail": officeEmail,
        "smartCardNumber": smartCardNumber,
        "firstBusAttendantName": firstBusAttendantName,
        "firstBusAttendantMobileNumber": firstBusAttendantMobileNumber,
        "totalSalary": totalSalary,
        "schemeId": schemeId,
        "appoinmentId": appoinmentId,
        "appoinmentFrom": appoinmentFrom,
        "lectureBased": lectureBased,
        "confirmationDate": confirmationDate,
        "renewalDate": renewalDate,
        "hostelId": hostelId,
        "documentList": documentList,
        "optionalSubjectsLists": optionalSubjectsLists,
        "studentEnquiryDetail": studentEnquiryDetail,
        "studentFeeSubmissionDetail": studentFeeSubmissionDetail,
        "studentShortName": studentShortName,
        "studentNameInReportCard": studentNameInReportCard,
        "batchName": batchName,
        "incrimentedEmployeeNumber": incrimentedEmployeeNumber,
        "schoolName": schoolName,
        "sectionName": sectionName,
      };
}
